package com.studytrade.studytrade2.view.implementations;

import java.util.ArrayList;
import java.util.List;

import com.studytrade.studytrade2.model.StudyTradeArticle;
import com.studytrade.studytrade2.model.StudyTradeUser;
import com.studytrade.studytrade2.view.interfaces.RegisterPageView;
import com.studytrade.studytrade2.view.interfaces.RegisterPageViewListener;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.Label;
import com.vaadin.ui.Layout;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button.ClickEvent;

public class RegisterPageViewImpl extends CustomStudyTradeComponent implements RegisterPageView {
	private static final long serialVersionUID = -2103599367448946610L;

	private List<RegisterPageViewListener> listeners = new ArrayList<>();

	private List<StudyTradeArticle> Articles;

	@AutoGenerated
	private NativeButton nativeButton_register;
	@AutoGenerated
	private PasswordField passwordField_2;
	@AutoGenerated
	private PasswordField passwordField_1;
	@AutoGenerated
	private TextField textField_mail;
	@AutoGenerated
	private TextField textField_Study;
	@AutoGenerated
	private NativeSelect nativeSelect_school;
	@AutoGenerated
	private TextField textField_city;
	@AutoGenerated
	private TextField textField_nickname;
	@AutoGenerated
	private TextField textField_lastname;
	@AutoGenerated
	private TextField textField_forename;
	@AutoGenerated
	private Label label_1;

	public RegisterPageViewImpl(StudyTradeUser usr, String searchstr, List<StudyTradeArticle> articles) {
		super(usr);

		this.Articles = articles;

		Init();

	}

	@Override
	public void addListener(RegisterPageViewListener listener) {
		listeners.add(listener);
	}

	@Override
	protected Layout buildLayout() {
		// common part: create layout
		VerticalLayout mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);

		Panel p = new Panel();
		VerticalLayout l = new VerticalLayout();

		// TODO Content
		// l.add alle Textfelder und Button Registrierung
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Registrierung");
		l.addComponent(label_1);

		// textField_forename
		textField_forename = new TextField();
		textField_forename.setCaption("Vorname");
		textField_forename.setImmediate(false);
		textField_forename.setWidth("-1px");
		textField_forename.setHeight("-1px");
		l.addComponent(textField_forename);

		// textField_lastname
		textField_lastname = new TextField();
		textField_lastname.setCaption("Nachname");
		textField_lastname.setImmediate(false);
		textField_lastname.setWidth("-1px");
		textField_lastname.setHeight("-1px");
		l.addComponent(textField_lastname);

		// textField_nickname
		textField_nickname = new TextField();
		textField_nickname.setCaption("Nickname");
		textField_nickname.setImmediate(false);
		textField_nickname.setWidth("-1px");
		textField_nickname.setHeight("-1px");
		l.addComponent(textField_nickname);

		// textField_city
		textField_city = new TextField();
		textField_city.setCaption("Wohnort");
		textField_city.setImmediate(false);
		textField_city.setWidth("-1px");
		textField_city.setHeight("-1px");
		l.addComponent(textField_city);

		// nativeSelect_school
		nativeSelect_school = new NativeSelect();
		nativeSelect_school.setCaption("Hochschule");
		nativeSelect_school.setImmediate(false);
		nativeSelect_school.setWidth("-1px");
		nativeSelect_school.setHeight("-1px");
		l.addComponent(nativeSelect_school);

		// textField_Study
		textField_Study = new TextField();
		textField_Study.setCaption("Studienrichtung");
		textField_Study.setImmediate(false);
		textField_Study.setWidth("-1px");
		textField_Study.setHeight("-1px");
		l.addComponent(textField_Study);

		// textField_mail
		textField_mail = new TextField();
		textField_mail.setCaption("E-Mail");
		textField_mail.setImmediate(false);
		textField_mail.setWidth("-1px");
		textField_mail.setHeight("-1px");
		l.addComponent(textField_mail);

		// passwordField_1
		passwordField_1 = new PasswordField();
		passwordField_1.setCaption("Passwort");
		passwordField_1.setImmediate(false);
		passwordField_1.setWidth("-1px");
		passwordField_1.setHeight("-1px");
		l.addComponent(passwordField_1);

		// passwordField_2
		passwordField_2 = new PasswordField();
		passwordField_2.setImmediate(false);
		passwordField_2.setWidth("-1px");
		passwordField_2.setHeight("-1px");
		l.addComponent(passwordField_2);

		// nativeButton_register
		nativeButton_register = new NativeButton();
		nativeButton_register.setCaption("Registrieren");
		nativeButton_register.setImmediate(false);
		nativeButton_register.setWidth("-1px");
		nativeButton_register.setHeight("-1px");
		l.addComponent(nativeButton_register);
		nativeButton_register.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				onBtnRegisterClicked();

			}
		});

		p.setContent(l);

		mainLayout.addComponent(p);

		return mainLayout;
	}

	@Override
	protected void onBtnRegisterClicked() {
		for (RegisterPageViewListener l : listeners) {
			// TODO ich weis nicht was hier rein kommt
			// das zugehörige Button ist nativeButton_register
		}

	}

	@Override
	protected void onBtnLoginClicked() {
		for (RegisterPageViewListener l : listeners)
			l.LoginClicked(edUsername.getValue(), edPassword.getValue());
	}

	@Override
	protected void onBtnSearchClicked() {
		for (RegisterPageViewListener l : listeners)
			l.SearchClicked(edSearch.getValue());
	}

	@Override
	protected void onBtnLogOffClicked() {
		for (RegisterPageViewListener l : listeners)
			l.LogOffClicked();
	}
}
