package com.studytrade.studytrade2.pages;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.Label;

public class ArticleObject extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = 9165111822095876107L;
	
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	public Embedded article_object_Picture;
	@AutoGenerated
	public Label article_object_Place;
	@AutoGenerated
	public Label article_object_Condition;
	@AutoGenerated
	public Label article_object_Price;
	@AutoGenerated
	public Label article_object_ArticleName;
	/**
	 * The constructor should first build the main layout, set the
	 *
	 * The constructor will not be automatically regenerated by the
	 */
	public ArticleObject() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	public void setArticleObject() {

	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setStyleName("article_object_main_layout");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("500px");
		mainLayout.setHeight("100px");

		// top-level component properties
		setWidth("500px");
		setHeight("100px");

		// article_object_ArticleName
		article_object_ArticleName = new Label();
		article_object_ArticleName.setStyleName("article_object_ArticleName");
		article_object_ArticleName.setImmediate(false);
		article_object_ArticleName.setWidth("300px");
		article_object_ArticleName.setHeight("30px");
		article_object_ArticleName.setValue("Artikelbezeichnung");
		mainLayout.addComponent(article_object_ArticleName, "top:0.0px;left:109.0px;");

		// article_object_Price
		article_object_Price = new Label();
		article_object_Price.setStyleName("article_object_Price");
		article_object_Price.setImmediate(false);
		article_object_Price.setWidth("60px");
		article_object_Price.setHeight("20px");
		article_object_Price.setValue("Preis");
		mainLayout.addComponent(article_object_Price, "top:60.0px;left:430.0px;");

		// article_object_Condition
		article_object_Condition = new Label();
		article_object_Condition.setStyleName("article_object_Condition");
		article_object_Condition.setImmediate(false);
		article_object_Condition.setWidth("80px");
		article_object_Condition.setHeight("26px");
		article_object_Condition.setValue("Zustand");
		mainLayout.addComponent(article_object_Condition, "top:34.0px;left:109.0px;");

		// article_object_Place
		article_object_Place = new Label();
		article_object_Place.setStyleName("article_object_Place");
		article_object_Place.setImmediate(false);
		article_object_Place.setWidth("80px");
		article_object_Place.setHeight("26px");
		article_object_Place.setValue("Ort");
		mainLayout.addComponent(article_object_Place, "top:34.0px;left:200.0px;");

		// article_object_Picture
		article_object_Picture = new Embedded();
		article_object_Picture.setStyleName("article_object_Picture");
		article_object_Picture.setImmediate(false);
		article_object_Picture.setWidth("100px");
		article_object_Picture.setHeight("100.0%");
		article_object_Picture.setSource(new ThemeResource("img/component/embedded_icon.png"));
		article_object_Picture.setType(1);
		article_object_Picture.setMimeType("image/png");
		mainLayout.addComponent(article_object_Picture, "top:0.0px;left:0.0px;");

		return mainLayout;
	}

}
