package com.studytrade.studytrade2.pages;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;

public class CommonPage extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,8","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":6} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private AbsoluteLayout commonpage_content_middle;
	@AutoGenerated
	private AbsoluteLayout commonpage_layout_right;
	@AutoGenerated
	private AbsoluteLayout commonpage_ads_left;
	@AutoGenerated
	private AbsoluteLayout commonpage_criteria_left;
	@AutoGenerated
	private AbsoluteLayout commonpage_categories_left;
	@AutoGenerated
	private AbsoluteLayout commonpage_searchbar_top;
	@AutoGenerated
	private TextField textField_3;
	@AutoGenerated
	private NativeSelect nativeSelect_3;
	@AutoGenerated
	private Button button_3;
	@AutoGenerated
	private AbsoluteLayout commonpage_user_bar_top;
	@AutoGenerated
	private MenuBar commonpage_usermenu_top_right;
	public boolean isLoggedIn = false;
	
	private static final long serialVersionUID = -6505966413920838613L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public CommonPage() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setStyleName("commonpage_main_layout");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// commonpage_user_bar_top
		commonpage_user_bar_top = buildCommonpage_user_bar_top();
		mainLayout.addComponent(commonpage_user_bar_top,
				"top:0.0px;right:0.0px;left:0.0px;");
		
		// commonpage_searchbar_top
		commonpage_searchbar_top = buildCommonpage_searchbar_top();
		mainLayout.addComponent(commonpage_searchbar_top,
				"top:20.0px;right:0.0px;left:0.0px;");
		
		// commonpage_categories_left
		commonpage_categories_left = new AbsoluteLayout();
		commonpage_categories_left.setStyleName("commonpage_categories_left");
		commonpage_categories_left.setImmediate(false);
		commonpage_categories_left.setWidth("200px");
		commonpage_categories_left.setHeight("300px");
		mainLayout.addComponent(commonpage_categories_left,
				"top:60.0px;left:0.0px;");
		
		// commonpage_criteria_left
		commonpage_criteria_left = new AbsoluteLayout();
		commonpage_criteria_left.setStyleName("commonpage_criteria_left");
		commonpage_criteria_left.setImmediate(false);
		commonpage_criteria_left.setWidth("200px");
		commonpage_criteria_left.setHeight("250px");
		mainLayout.addComponent(commonpage_criteria_left,
				"top:360.0px;left:0.0px;");
		
		// commonpage_ads_left
		commonpage_ads_left = new AbsoluteLayout();
		commonpage_ads_left.setStyleName("commonpage_ads_left");
		commonpage_ads_left.setImmediate(false);
		commonpage_ads_left.setWidth("200px");
		commonpage_ads_left.setHeight("200px");
		mainLayout.addComponent(commonpage_ads_left, "top:610.0px;left:0.0px;");
		
		// commonpage_layout_right
		commonpage_layout_right = new AbsoluteLayout();
		commonpage_layout_right.setStyleName("commonpage_layout_right");
		commonpage_layout_right.setImmediate(false);
		commonpage_layout_right.setWidth("150px");
		commonpage_layout_right.setHeight("800px");
		mainLayout.addComponent(commonpage_layout_right,
				"top:60.0px;right:0.0px;");
		
		// commonpage_content_middle
		commonpage_content_middle = new AbsoluteLayout();
		commonpage_content_middle.setStyleName("commonpage_content_middle");
		commonpage_content_middle.setImmediate(false);
		commonpage_content_middle.setWidth("100.0%");
		commonpage_content_middle.setHeight("488px");
		mainLayout.addComponent(commonpage_content_middle,
				"top:80.0px;right:20.0%;left:20.0%;");
		
		return mainLayout;
	}

	@AutoGenerated
	private AbsoluteLayout buildCommonpage_user_bar_top() {
		// common part: create layout
		commonpage_user_bar_top = new AbsoluteLayout();
		commonpage_user_bar_top.setStyleName("commonpage_user_bar_top");
		commonpage_user_bar_top.setImmediate(false);
		commonpage_user_bar_top.setWidth("100.0%");
		commonpage_user_bar_top.setHeight("20px");
		
		if(isLoggedIn){
		// commonpage_usermenu_top_right
		commonpage_usermenu_top_right = new MenuBar();
		commonpage_usermenu_top_right
				.setStyleName("commonpage_usermenu_top_right");
		commonpage_usermenu_top_right.setImmediate(false);
		commonpage_usermenu_top_right.setWidth("-1px");
		commonpage_usermenu_top_right.setHeight("100.0%");
		com.vaadin.ui.MenuBar.MenuItem menu_messages = commonpage_usermenu_top_right.addItem("Nachrichten", null, null);
		com.vaadin.ui.MenuBar.MenuItem menu_history = commonpage_usermenu_top_right.addItem("Verlauf", null, null);
		com.vaadin.ui.MenuBar.MenuItem menu_mypage = commonpage_usermenu_top_right.addItem("Meine Seite", null, null);
		com.vaadin.ui.MenuBar.MenuItem menu_logout = commonpage_usermenu_top_right.addItem("Logout", null, null);
		commonpage_user_bar_top.addComponent(commonpage_usermenu_top_right,
				"top:0.0px;right:0.0px;");	
		
		} else {
			TextField commonpage_username_top = new TextField("Username");
			PasswordField commonpage_password_top = new PasswordField("Passwort");
			commonpage_username_top.setStyleName("commonpage_top_small_fields");
			commonpage_password_top.setStyleName("commonpage_top_small_fields");
			Button commonpage_login_button_top = new Button("Login");
			commonpage_user_bar_top.addComponent(commonpage_username_top, "top:1px;right:238px");
			commonpage_user_bar_top.addComponent(commonpage_password_top, "top:1px;right:100px");
			commonpage_user_bar_top.addComponent(commonpage_login_button_top, "top:0px;right:10px");
		}
		return commonpage_user_bar_top;
	}

	@AutoGenerated
	private AbsoluteLayout buildCommonpage_searchbar_top() {
		// common part: create layout
		commonpage_searchbar_top = new AbsoluteLayout();
		commonpage_searchbar_top.setStyleName("commonpage_searchbar_top");
		commonpage_searchbar_top.setImmediate(false);
		commonpage_searchbar_top.setWidth("100.0%");
		commonpage_searchbar_top.setHeight("40px");
		
		// button_3
		button_3 = new Button();
		button_3.setCaption("Button");
		button_3.setImmediate(true);
		button_3.setWidth("-1px");
		button_3.setHeight("-1px");
		commonpage_searchbar_top.addComponent(button_3,
				"top:8.0px;left:525.0px;");
		
		// nativeSelect_3
		nativeSelect_3 = new NativeSelect();
		nativeSelect_3.setImmediate(false);
		nativeSelect_3.setWidth("-1px");
		nativeSelect_3.setHeight("-1px");
		commonpage_searchbar_top.addComponent(nativeSelect_3,
				"top:11.0px;left:439.0px;");
		
		// textField_3
		textField_3 = new TextField();
		textField_3.setImmediate(false);
		textField_3.setWidth("200px");
		textField_3.setHeight("100.0%");
		commonpage_searchbar_top.addComponent(textField_3,
				"top:0.0px;left:224.0px;");
		
		return commonpage_searchbar_top;
	}

}
