package com.studytrade.studytrade2.pages;

import com.studytrade.studytrade2.StudyTradePresenter;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.UI;

public class LandingPage extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	
	
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_2;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_3;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;
	@AutoGenerated
	private Button landingpage_button_login;
	@AutoGenerated
	private Button landingpage_button_register;
	@AutoGenerated
	private PasswordField landing_page_passwordfield;
	@AutoGenerated
	private TextField landing_page_textfield_username;
	@AutoGenerated
	private AbsoluteLayout landingpage_absolutLayout;
	@AutoGenerated
	private Embedded landingpage_banner_top;
	private Button bt_search;
	private TextField tf_search;
	final StudyTradePresenter studyTradePresenter;
	private static final long serialVersionUID = -4191194848571406037L;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 * 
	 * @param presenter
	 */
	public LandingPage(StudyTradePresenter presenter) {
		this.studyTradePresenter = presenter;
		buildMainLayout();
		setCompositionRoot(mainLayout);

		bt_search.addClickListener(new Button.ClickListener() {
			
			/**
			 * 
			 */
			private static final long serialVersionUID = 3815438412793829878L;

			@Override
			public void buttonClick(ClickEvent event) {
				System.out.println(tf_search.getValue());
				/*TODO das wirft unendliche Exceptions ... */
				//studyTradePresenter.Searching(tf_search.getValue());
			}
		});
		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		int browser_height = UI.getCurrent().getPage().getBrowserWindowHeight();
		mainLayout.setHeight(String.valueOf(browser_height));
		mainLayout.setWidth("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// absoluteLayout_2
		absoluteLayout_2 = buildAbsoluteLayout_2();
		mainLayout.addComponent(absoluteLayout_2,
				"top:10%;right:10.0%;bottom:10.0%;left:10.0%;");

		return mainLayout;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_2() {
		// common part: create layout
		absoluteLayout_2 = new AbsoluteLayout();
		absoluteLayout_2.setImmediate(false);
		absoluteLayout_2.setWidth("100.0%");
		absoluteLayout_2.setHeight("100.0%");

		// landingpage_absolutLayout
		landingpage_absolutLayout = buildLandingpage_absolutLayout();
		absoluteLayout_2.addComponent(landingpage_absolutLayout,
				"top:0.0px;right:0.0px;bottom:10.0%;left:0.0px;");

		// absoluteLayout_3
		absoluteLayout_3 = buildAbsoluteLayout_3();
		absoluteLayout_2.addComponent(absoluteLayout_3,
				"top:90.0%;right:0.0px;bottom:0.0px;left:0.0px;");

		return absoluteLayout_2;
	}

	@AutoGenerated
	private AbsoluteLayout buildLandingpage_absolutLayout() {
		// common part: create layout
		landingpage_absolutLayout = new AbsoluteLayout();
		landingpage_absolutLayout.setStyleName("landingpage_absolutLayout");
		landingpage_absolutLayout.setImmediate(false);
		landingpage_absolutLayout.setWidth("100.0%");
		landingpage_absolutLayout.setHeight("100.0%");

		// Suchfeld
		tf_search = new TextField();
		bt_search = new Button("Suchen");
		landingpage_absolutLayout.addComponent(tf_search,
				"top:90px; right:30px;");
		landingpage_absolutLayout.addComponent(bt_search,
				"top:130px; right:30px;");

		// landingpage_banner_top
		landingpage_banner_top = new Embedded();
		landingpage_banner_top.setStyleName("landingpage_banner_top");
		landingpage_banner_top.setImmediate(false);
		landingpage_banner_top.setWidth("100.0%");
		landingpage_banner_top.setHeight("80px");
		landingpage_banner_top.setSource(new ThemeResource(
				"img/component/StudyTrade.png"));
		landingpage_banner_top.setType(1);
		landingpage_banner_top.setMimeType("image/png");
		landingpage_absolutLayout.addComponent(landingpage_banner_top,
				"top:0.0px;right:0.0px;left:0.0px;");

		return landingpage_absolutLayout;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_3() {
		// common part: create layout
		absoluteLayout_3 = new AbsoluteLayout();
		absoluteLayout_3.setStyleName("landingpage_absolutLayout_login_bottom");
		absoluteLayout_3.setImmediate(false);
		absoluteLayout_3.setWidth("100.0%");
		absoluteLayout_3.setHeight("100.0%");

		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		absoluteLayout_3.addComponent(horizontalLayout_3,
				"top:1.0px;right:0.0px;left:50.0%;");

		return absoluteLayout_3;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("100.0%");
		horizontalLayout_3.setHeight("100.0%");
		horizontalLayout_3.setMargin(false);

		// landing_page_textfield_username
		landing_page_textfield_username = new TextField();
		landing_page_textfield_username
				.setStyleName("landing_page_textfield_username");
		landing_page_textfield_username.setCaption("Username");
		landing_page_textfield_username.setImmediate(false);
		landing_page_textfield_username.setWidth("-1px");
		landing_page_textfield_username.setHeight("-1px");
		horizontalLayout_3.addComponent(landing_page_textfield_username);
		horizontalLayout_3.setComponentAlignment(
				landing_page_textfield_username, new Alignment(33));

		// landing_page_passwordfield
		landing_page_passwordfield = new PasswordField();
		landing_page_passwordfield.setStyleName("landing_page_passwordfield");
		landing_page_passwordfield.setCaption("Passwort");
		landing_page_passwordfield.setImmediate(false);
		landing_page_passwordfield.setWidth("-1px");
		landing_page_passwordfield.setHeight("-1px");
		horizontalLayout_3.addComponent(landing_page_passwordfield);
		horizontalLayout_3.setComponentAlignment(landing_page_passwordfield,
				new Alignment(33));

		// landingpage_button_register
		landingpage_button_register = new Button();
		landingpage_button_register.setStyleName("landingpage_button_register");
		landingpage_button_register.setCaption("Registrierung");
		landingpage_button_register.setImmediate(true);
		landingpage_button_register.setWidth("-1px");
		landingpage_button_register.setHeight("-1px");
		horizontalLayout_3.addComponent(landingpage_button_register);
		horizontalLayout_3.setComponentAlignment(landingpage_button_register,
				new Alignment(33));

		// landingpage_button_login
		landingpage_button_login = new Button();
		landingpage_button_login.setStyleName("landingpage_button_login");
		landingpage_button_login.setCaption("Login");
		landingpage_button_login.setImmediate(true);
		landingpage_button_login.setWidth("-1px");
		landingpage_button_login.setHeight("-1px");
		horizontalLayout_3.addComponent(landingpage_button_login);
		horizontalLayout_3.setComponentAlignment(landingpage_button_login,
				new Alignment(33));

		return horizontalLayout_3;
	}

}
