package com.studytrade.studytrade2.pages;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;

public class LoginPage extends CommonPage {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private AbsoluteLayout logingArea;
	@AutoGenerated
	private Button btn_forgotPw;
	@AutoGenerated
	private Button btn_Login;
	@AutoGenerated
	private PasswordField passwordField_LoginPage;
	@AutoGenerated
	private Label lbnPassword;
	@AutoGenerated
	private TextField txt_Email;
	@AutoGenerated
	private Label lbnEmail;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public LoginPage() {
		super();
		
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setStyleName("commonpage_main_layout");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// logingArea
		logingArea = buildLogingArea();
		mainLayout.addComponent(logingArea, "top:80.0px;right:25.0%;bottom:25.0%;left:25.0%;");
		
		return mainLayout;
	}

	@AutoGenerated
	private AbsoluteLayout buildLogingArea() {
		// common part: create layout
		logingArea = new AbsoluteLayout();
		logingArea.setImmediate(false);
		logingArea.setWidth("100.0%");
		logingArea.setHeight("100.0%");
		
		// lbnEmail
		lbnEmail = new Label();
		lbnEmail.setImmediate(false);
		lbnEmail.setWidth("60px");
		lbnEmail.setHeight("18px");
		lbnEmail.setValue("Email:");
		logingArea.addComponent(lbnEmail, "top:62.0px;left:45.0px;");
		
		// txt_Email
		txt_Email = new TextField();
		txt_Email.setImmediate(false);
		txt_Email.setWidth("-1px");
		txt_Email.setHeight("-1px");
		logingArea.addComponent(txt_Email, "top:80.0px;left:45.0px;");
		
		// lbnPassword
		lbnPassword = new Label();
		lbnPassword.setImmediate(false);
		lbnPassword.setWidth("-1px");
		lbnPassword.setHeight("-1px");
		lbnPassword.setValue("Passwort:");
		logingArea.addComponent(lbnPassword, "top:120.0px;left:45.0px;");
		
		// passwordField_LoginPage
		passwordField_LoginPage = new PasswordField();
		passwordField_LoginPage.setImmediate(false);
		passwordField_LoginPage.setWidth("-1px");
		passwordField_LoginPage.setHeight("24px");
		logingArea.addComponent(passwordField_LoginPage, "top:140.0px;left:45.0px;");
		
		// btn_Login
		btn_Login = new Button();
		btn_Login.setCaption("Login");
		btn_Login.setImmediate(false);
		btn_Login.setWidth("100px");
		btn_Login.setHeight("26px");
		logingArea.addComponent(btn_Login, "top:180.0px;left:45.0px;");
		
		// btn_forgotPw
		btn_forgotPw = new Button();
		btn_forgotPw.setCaption("Passwort vergessen?");
		btn_forgotPw.setImmediate(false);
		btn_forgotPw.setWidth("-1px");
		btn_forgotPw.setHeight("-1px");
		logingArea.addComponent(btn_forgotPw, "top:180.0px;left:205.0px;");
		
		return logingArea;
	}

}
